QHEROQUEST_ROOT = $$PWD

QHEROQUEST_INCLUDE = $$QHEROQUEST_ROOT/include/ 

QHEROQUEST_BIN = $$QHEROQUEST_ROOT/bin

QHEROQUEST_OBJ = $$QHEROQUEST_ROOT/obj

QHEROQUEST_INSTALL_PLUGINS = $$QHEROQUEST_ROOT/plugins

INCLUDEPATH += $$QHEROQUEST_INCLUDE

DEPENDPATH += $$QHEROQUEST_INCLUDE

DESTDIR = $$QHEROQUEST_BIN

